version: 2
jobs:
  build:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

      # build and push Docker image
      - run: |
          ./scrapyd-deploy/docker-build.sh
